export const REQUEST_CREATE_USER = "REQUEST_CREATE_USER";
export const SUCCESS_CREATE_USER = "SUCCESS_CREATE_USER";
export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const SUCCESS_LOGIN_USER = "SUCCESS_LOGIN_USER";
